baseURL = "https://blissful-yalow-86b060.netlify.app/"
languageCode = "en-us"
title = "JAMSite"
theme = "tale"
copyright = "Copyright 2019 Stackacademy.tv"
disableKinds = ["section"]

[outputs]
	home = ["HTML", "JSON"]
