backend:
    name: github
    repo: patchampoux/jamsite

media_folder: static/images/uploads
public_folder: /images/uploads

collections:
    - name: pages
      label: Pages
      folder: content/
      create: true
      path: '{{slug}}'
      fields:
          - label: Title
            name: title
            widget: string
          - label: Author
            name: author
            widget: select
            options: ['Ray Viljoen', 'Jane Doe']
          - label: Date
            name: date
            widget: datetime
          - label: Content
            name: body
            widget: markdown
    - name: premium-pages
      label: Premium Pages
      folder: content/premium
      create: true
      path: '{{slug}}'
      fields:
          - label: Title
            name: title
            widget: string
          - label: Content
            name: body
            widget: markdown
